FROM node:18-alpine
WORKDIR /app 
ENV PATH /app/node_modules/.bin:$PATH
COPY package*.json .
RUN npm install 
COPY . .
RUN npm run build

FROM nginx
COPY --from=build /app/build /usr/share/nginx/html

#DONE